sudo: required
language: go
services:
- docker
go:
- 1.11.x
env:
- GO111MODULE=on
go_import_path: github.com/buildpack/packs
install:
- set -e
- ./cf/bin/build cflinuxfs3
script:
- test -z "$(bin/format | tee >(cat >&2))"
- ./cf/bin/test cflinuxfs3
